add Buffer(Vec<u8>) support for RedisValue
RedisLabsModules/redismodule-rs pull request #161
Opened 2021-07-08 09:04 UTC by gkorland

2021-07-08 09:53 UTC, gavrie requested changes

2021-07-08 09:53 UTC, gavrie commented on src/redisvalue.rs
> +    Buffer(Vec<u8>),
For consistency, I think we should call this `StringBuffer` instead of `Buffer`. We're talking about yet another way to represent a Redis String.

2021-07-11 14:46 UTC, oshadmi commented on src/context/mod.rs
> +                    s.len() as usize,
Can Vec len and the corresponding StringBuffer len be different (when bytes count does not match the character count in utf-8)
No need to call `from_utf8` or `into_string_lossy` or some conversion/validation functions?

2021-07-14 07:28 UTC, oshadmi approved these changes
👍🏼

2021-07-18 14:19 UTC, merged