Add get_redis_command
RedisLabsModules/redismodule-rs pull request #184
Opened 2021-08-10 05:43 UTC by oshadmi

2021-08-12 10:13 UTC, gavrie requested changes

2021-08-12 10:13 UTC, gavrie commented on src/context/mod.rs
> +    }
No sure why you made this a method of `Context`...
In general, the version parsing is spread out over 3 functions: This one, `get_redis_version_internal` and `Version::from`.
The regex parsing also has some duplication.
What I suggest is: Write 1 function that parses the `info` response directly into a `Version`. You can use 3 capture groups to directly extract the major/minor/patch without later needing to split on `.`. This should be fairly simple and clean.

2021-08-19 07:52 UTC, oshadmi commented on tests/integration.rs
> +        (res[0] == 6 && res[1] == 2 && res[2] >= 3) || (res[0] == 6 && res[1] == 0 && res[2] >= 15)
Fixed to test for major > 0

2022-01-02 07:40 UTC, gkorland requested changes

2022-01-02 07:40 UTC, gkorland commented on Makefile
> +	cargo build --features test --example test_helper --all-targets  $(CARGO_FLAGS)
```suggestion
	cargo build --features experimental-api,test --all --all-targets  $(CARGO_FLAGS)
```

2022-01-02 07:40 UTC, gkorland commented on build.sh
> +cargo build --features test --example test_helper --all-targets
```suggestion
cargo build --features experimental-api,test --all --all-targets
```

2022-02-09 08:43 UTC, gkorland approved these changes

2022-02-09 08:47 UTC, merged