Make call function generic.
RedisLabsModules/redismodule-rs pull request #264
Opened 2023-01-19 15:48 UTC by MeirShpilraien

2023-01-24 10:40 UTC, gkorland commented on src/redismodule.rs
> +    pub fn create_from_slice(ctx: *mut raw::RedisModuleCtx, s: &[u8]) -> Self {
```suggestion
    #[allow(clippy::not_unsafe_ptr_arg_deref)]
    pub fn create_from_slice(ctx: *mut raw::RedisModuleCtx, s: &[u8]) -> Self {
```

2023-01-24 10:44 UTC, gkorland requested changes

2023-01-24 10:44 UTC, gkorland commented on src/redismodule.rs
> +    pub fn create_from_slice(ctx: *mut raw::RedisModuleCtx, s: &[u8]) -> Self {
```suggestion
    #[allow(clippy::not_unsafe_ptr_arg_deref)]
    pub fn create_from_slice(ctx: *mut raw::RedisModuleCtx, s: &[u8]) -> Self {
```

2023-01-24 10:44 UTC, gkorland commented on src/redismodule.rs
> +            raw::RedisModule_CreateString.unwrap()(ctx, s.as_ptr() as *const c_char, s.len())
```suggestion
            raw::RedisModule_CreateString.unwrap()(ctx, s.as_ptr().cast::<c_char>(), s.len())
```

2023-01-24 10:44 UTC, gkorland commented on src/context/mod.rs
> +    phantom: std::marker::PhantomData<&'a u64>, // allows to make sure the object will not leave longer than actaull arguments slice
```suggestion
    // Phantom is used to make sure the object will not live longer than actual arguments slice
    phantom: std::marker::PhantomData<&'a raw::RedisModuleString>,
```

2023-01-24 10:44 UTC, gkorland commented on src/context/mod.rs
> +            }
```suggestion
            self.args.iter_mut().for_each(|v| unsafe {
                raw::RedisModule_FreeString.unwrap()(std::ptr::null_mut(), *v)
            });
```

2023-01-24 10:45 UTC, gkorland commented
@MeirShpilraien few minor comments

2023-01-24 12:32 UTC, MeirShpilraien commented
@gkorland merged

2023-01-25 16:20 UTC, gkorland commented
@MeirShpilraien some conflicts

2023-01-26 11:41 UTC, MeirShpilraien commented
@gkorland fixed.

2023-02-01 09:49 UTC, gkorland approved these changes

2023-02-01 10:16 UTC, merged